### ISSUE TITLE
Some tags doesn't seem to be properly parsed

### ISSUE THREAD

**Issue by thiagomajesk** [xinz/sax_map#1]
Hi! 

I was testing this library today while parsing some RSS feeds and I think I've encountered a problem...
Some tags are not getting parsed properly, take this feed as an example: https://www.gamespot.com/feeds/mashup:

```xml
<rss xmlns:atom="http://www.w3.org/2005/Atom" xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:media="http://search.yahoo.com/mrss/" version="2.0">
<channel>
<title>GameSpot - All Content</title>
<link>https://www.gamespot.com/feeds/mashup/</link>
<description>GameSpot's Everything Feed! All the latest from GameSpot</description>
<language>en-us</language>
<lastBuildDate>Sun, 05 Jul 2020 08:11:33 -0700</lastBuildDate>
<atom:link href="https://www.gamespot.com/feeds/mashup/" rel="self"/>
<item>
<title>Blankos Block Party Is A User Generated Playground</title>
<link>https://www.gamespot.com/videos/blankos-block-party-is-a-user-generated-playground/2300-6453301/</link>
<description>
<![CDATA[ Michael Higham sat down with Blankos Block Party's chief creative officer Jamie Jackson to discuss user generated content and how the free to play model will work. ]]>
</description>
<guid isPermaLink="false">2300-6453301</guid>
<pubDate>Sun, 05 Jul 2020 07:00:00 -0700</pubDate>
<media:content url="https://gamespot1.cbsistatic.com/uploads/screen_medium/1430/14303732/3694227-p4a_blankosint_20200702_site.jpg" type="image/jpeg" width="480" height="270"/>
<dc:creator/>
<category/>
</item>
<item>
...
```

After parsed I get something like:

```elixir
{:ok,
 %{
   "rss" => %{
     "channel" => %{
       "atom:link" => %{},
       "description" => "GameSpot's Everything Feed! All the latest from GameSpot",
       "item" => [
         %{
           "category" => %{},
           "dc:creator" => %{},
           "description" => "Michael Higham sat down with Blankos Block Party's chief creative officer Jamie Jackson to discuss user generated content and how the free to play model will work.",
           "guid" => "2300-6453301",
           "link" => "https://www.gamespot.com/videos/blankos-block-party-is-a-user-generated-playground/2300-6453301/",
           "media:content" => %{},
           "pubDate" => "Sun, 05 Jul 2020 07:00:00 -0700",
           "title" => "Blankos Block Party Is A User Generated Playground"
         },
```

It seems that self-closing tags are not getting parsed with value even though they have attributes, for example:

```xml
<media:content url="https://gamespot1.cbsistatic.com/uploads/screen_medium/1430/14303732/3694227-p4a_blankosint_20200702_site.jpg" type="image/jpeg" width="480" height="270"/>
<dc:creator/>
<category/>
```

Returns:

```elixir
%{"media:content" => %{}, "dc:creator" => %{}, "category" => %{}}
```

It should be:

```elixir
%{
    "media:content" => 
     %{
        "url" => "https://gamespot1.cbsistatic.com/uploads/screen_medium/1430/14303732/3694227-p4a_blankosint_20200702_site.jpg",
        "type" => "image/jpeg", 
        "width" => "480", 
        "height" => "270"
    },
    "dc:creator" => %{}, 
    "category" => %{}
}
```

**Comment by xinz** [comment]
@thiagomajesk hello, thanks for your report, currently, this library does not process attributes of nodes.

Let's take a look at the example:

```
<media:content url="https://gamespot1.cbsistatic.com/uploads/screen_medium/1430/14303732/3694227-p4a_blankosint_20200702_site.jpg" type="image/jpeg" width="480" height="270"/>
<dc:creator/>
<category/>
```

If we process the attributes of `media:content` node and return as the following, from the map result's perspective, the `url` / `type` / `width` / `height` attributes would be considered as the children nodes of `media:content`, but they are attributes.

```
%{
    "media:content" => 
     %{
        "url" => "https://gamespot1.cbsistatic.com/uploads/screen_medium/1430/14303732/3694227-p4a_blankosint_20200702_site.jpg",
        "type" => "image/jpeg", 
        "width" => "480", 
        "height" => "270"
    }
}
```

Still in this case, if we imagine an example like this:

```
<media:content url="external">
  <url>https://gamespot1.cbsistatic.com/uploads/screen_medium/1430/14303732/3694227-p4a_blankosint_20200702_site.jpg</url>
</media:content>
```

The `url` value of map result should be the `https://...` or `external` value?

I see other similar library would process attribute as `-url` to distinct children node, what do you think about it?

**Comment by thiagomajesk** [comment]
@xinz Hi again!

Yes, of course, you are right! I should've included this scenario in my original post.

Bear in mind that syntactically speaking, there are no differences from using attributes and nodes in XML. 
Also, notice that for a well-formed XML (a.ka parseable XML) this structure would be very uncommon to happen.

That being said, I'd say that there are at least some options:

- Proactively favor element/ node definitions instead of attributes (like many parsers do)
- Uniquely merge attributes and nodes, favoring one or the other
- Prefix the attributes, like you already pointed out. I've actually seen the same pattern but using `@` instead

**Comment by xinz** [comment]
Thanks for your summary, please correct me if any missing, we would do the following supports:

1. Keep current logic to ignore the attributes by default;
2. Add a option to fetch attributes of element with `@` as the prefix of the key name of map;
3. Add a option to fetch attributes as well, but process them like the children elements, and maybe override by the same naming children elements if possible.

#2 and #3 are mutually exclusive.

**Comment by thiagomajesk** [comment]
@xinz Hi again!

No problem, I'm the one who should be thanking you! 😄

> #2 and #3 are mutually exclusive.

Yes, I actually meant one of the three options (the first one being what the lib already does).

Notice that all of the options have drawbacks too. 
For prefixes, both `-` and `@` are valid XML attribute names, so: `<node @foo="foo" -bar="bar">` might get weird.

Another solution would be to let the user select which approach he wants through options, something like: 

```elixir
SAXMap.from_string(xml, attribute_strategy: :ignore)
SAXMap.from_string(xml, attribute_strategy: :prefix)
SAXMap.from_string(xml, attribute_strategy: :override)
```

Cheers!

**Comment by xinz** [comment]
Hello, @thiagomajesk, thanks for your suggestions : )

I like your mentioned way to implement, and here are some tweak base on that, could you please take a look?

```
SAXMap.from_string(xml, attribute_strategy: :ignore)
SAXMap.from_string(xml, attribute_strategy: {:prefix, your_prefer_prefix_str})
SAXMap.from_string(xml, attribute_strategy: :override)
```

Once confirm this requirement, we can plan to add this feature.

**Comment by thiagomajesk** [comment]
@xinz 

I don't know if I like the idea of mixing data types for options like that. For me at least is a little bit confusing.
Do you know another lib that also uses something like that? (Just for reference).

I would be more inclined to use something like:

```elixir
SAXMap.from_string(xml, attribute_strategy: :ignore)
SAXMap.from_string(xml, attribute_strategy: :prefix, attribute_prefix: "@") # Defaults to whatever you want
SAXMap.from_string(xml, attribute_strategy: :override)
```

I'm not 100% sure. I think whatever you like better will do 😅.

**Update:** I discovered today that `Ecto.Adapters.SQL.Sandbox.mode/2` does exactly that you proposed with the `:shared` option. You use it like this: ` Ecto.Adapters.SQL.Sandbox.mode(Repo, {:shared, self()})` or `Ecto.Adapters.SQL.Sandbox.mode(Repo, :auto)`.

**Comment by xinz** [comment]
@thiagomajesk thanks, I will add it later.

**Comment by xinz** [comment]
@thiagomajesk when deep in the development, the follow result is in our expection?

```elixir
xml = """
      <data attr1="1" attr2="false" item3="in_attr">
        <item1>item_value</item1>
        <item2>true</item2>
        <item3>in_child</item3>
        <groups group_name="test">
          <group attr="1">gc1</group>
          <group attr="2">gc2</group>
          <group attr="3">gc3</group>
          <group attr="4">gc4</group>
        </groups>
      </data>
    """
```

After the transfer into a map:

```elixir
%{
   "data" => %{
     "attr1" => "1",
     "attr2" => "false",
     "groups" => %{
       "attr" => ["1", "2", "3", "4"],
       "group" => ["gc1", "gc2", "gc3", "gc4"],
       "group_name" => "test"
     },
     "item1" => "item_value",
     "item2" => "true",
     "item3" => "in_child"
   }
 }
```

Process parent's attributes as its sub-children elements, e.g. `attr1` is with the peer of `item1`.

The "groups" of the above result has `attr` and `group` elements both are list, here are expected, but from the use case,
it is seems difficult to fetch the second `group` element and its attributes "2".

I have finished the original design local, but I would like to do some changes like this:

Follow `Saxy.Handler`'s rule to process event to distinct element's name and attributes in a `tuple`

```elixir
def handle_event(:start_element, {name, attributes}, state) do
    {:ok, [{:start_element, name, attributes} | state]}
end
```

Still with the same input XML content, and the result as follows, the key change is to keep the children elements and current node attributes in a `tuple` if attributes are existed, this process can use for fetch-attributes-flow, could you please give some feedback from your use cases?

```elixir
%{
   "data" => {%{
      "groups" => {%{
         "group" => [
           {"gc1", %{"attr" => "1"}},
           {"gc2", %{"attr" => "2"}},
           {"gc3", %{"attr" => "3"}},
           {"gc4", %{"attr" => "4"}}
         ]
       }, %{"group_name" => "test"}},
      "item1" => "item_value",
      "item2" => "true",
      "item3" => "in_child"
    }, %{"attr1" => "1", "attr2" => "false", "item3" => "in_attr"}}
 }
```

**Edit**: Sorry that I notice if we change return it as `tuple`, it does not a single map will make more complex for iterate/fetch item(s), so I will give up the above `tuple` comment.

**Comment by xinz** [comment]
@thiagomajesk I have committed this implement in the master branch, after some thinking in the development I find the above `#2`(prefix) and `#3`(override) items are very similar, so I have changed the option as `ignore_attribute` as true | false | {false, prefix}, by default this option is true.

Here are some example for your reference, could you please take a look again for your use case, if it looks good for use, I will release a new version.

```
xml = """
  <data attr1="1" attr2="false" item3="override">
    <item1>item_value1</item1>
    <item2>item_value2</item2>
    <item3>item_value3</item3>
    <groups>
      <group attr="1">a</group>
      <group attr="2">b</group>
    </groups>
  </data>
"""

SAXMap.from_string(xml, ignore_attribute: false)

{:ok,
  %{
    "data" => %{
      "attr1" => "1",
      "attr2" => "false",
      "groups" => %{"attr" => ["1", "2"], "group" => ["a", "b"]},
      "item1" => "item_value1",
      "item2" => "item_value2",
      "item3" => "item_value3"
    }
  }}

SAXMap.from_string(xml, ignore_attribute: {false, "@"})

{:ok,
  %{
    "data" => %{
      "@attr1" => "1",
      "@attr2" => "false",
      "@item3" => "override",
      "groups" => %{"@attr" => ["1", "2"], "group" => ["a", "b"]},
      "item1" => "item_value1",
      "item2" => "item_value2",
      "item3" => "item_value3"
    }
  }}
```

**Comment by thiagomajesk** [comment]
@xinz Sorry for the delay...

I'll try to respond to both of your comments by taking your previous example... 
I couldn't see the similarity you have mentioned, but I think it should actually be something like the example bellow:

**PS.:** I think I found more cases where it's relevant to have options to remove ambiguity

```elixir
xml = """
  <data attr1="1" attr2="false" item3="override">
    <item1>item_value1</item1>
    <item2>item_value2</item2>
    <item3>item_value3</item3>
    <groups>
      <group attr="1">a</group>
      <group attr="2">b</group>
    </groups>
  </data>
"""

# Ignores attribute values (default)
SAXMap.from_string(xml, strategy: {:ignore, :attribute})

# {:ok,
#  %{
#    "data" => %{
#      "groups" => ["a", "b"],
#      "item1" => "item_value1",
#      "item2" => "item_value2",
#      "item3" => "item_value3"
#    }
#  }}

# Ignores node values (not node children)
SAXMap.from_string(xml, strategy: {:ignore, :node})

# {:ok,
#  %{
#    "data" => %{
#      "attr1" => "1",
#      "attr2" => "false",
#      "item3" => "override"
#      "groups" => [%{"attr" => 1}, %{"attr" => 2}]
#    }
#  }}

# Override existing key with node value
SAXMap.from_string(xml, strategy: {:override, :node})

# {:ok,
#  %{
#    "data" => %{
#      "attr1" => "1",
#      "attr2" => "false",
#      "groups" => ["a", "b"],
#      "item1" => "item_value1",
#      "item2" => "item_value2",
#      "item3" => "override" # Here the node "item3" was overridden by the attribute
#    }
#  }}

# Override existing key with attribute value
SAXMap.from_string(xml, strategy: {:override, :attribute})

# {:ok,
#  %{
#    "data" => %{
#      "attr1" => "1",
#      "attr2" => "false",
#      "item3" => "item_value3" # Here the attribute "item3" was overridden by the node
#      "groups" => ["a", "b"],
#      "item1" => "item_value1",
#      "item2" => "item_value2",
#    }
#  }}

# Prefix all attributes keys with the given value
SAXMap.from_string(xml, strategy: {:prefix, "@"})

# {:ok,
#  %{
#    "data" => %{
#      "attr1" => "1",
#      "attr2" => "false",
#      "@item3" => "override",
#      "groups" => ["a", "b"],
#      "item1" => "item_value1",
#      "item2" => "item_value2",
#      "item3" => "item_value3"
#    }
#  }}
```

I think this example covers all possible cases. Cheers!

**Comment by xinz** [comment]
Thanks again for your suggestions.

> I couldn't see the similarity you have mentioned

During develop the implemented part, I find the default "prefix" (let's assume it is `""`) equals the "override" refer the original comment, since in the SAX mode, we fetch the current node's attribute(s) first, and then process the current node's child nodes, so far the same key(from the attribute's key) is always override by the node's name if theirs keys are conflicted.

```
SAXMap.from_string(xml, attribute_strategy: :prefix, attribute_prefix: "@") # Defaults to whatever you want
SAXMap.from_string(xml, attribute_strategy: :override)
```

Here are some comments to your suggestions:

1, As usual, there exists a scenario only care XML's attributes case?

```
# Ignores node values (not node children)
SAXMap.from_string(xml, strategy: {:ignore, :node})
```

2, When we describe `{:override, :node}` / `{:override, :attribute}`, I feel it is obscure, maybe `:overridden_by` possible?

```
SAXMap.from_string(xml, strategy: {:override, :node})
SAXMap.from_string(xml, strategy: {:override, :attribute})
```

3, I also feel this definition is obscure, since it does not talk about the `attribute` related literally.

```
SAXMap.from_string(xml, strategy: {:prefix, "@"})
```

Could you please share that the current implemented is satisfy for your use case?

**Comment by thiagomajesk** [comment]
@xinz You are welcome!

> During develop the implemented part, I find the default "prefix" (let's assume it is "") equals the "override" refer the original comment, since in the SAX mode, we fetch the current node's attribute(s) first, and then process the current node's child nodes, so far the same key(from the attribute's key) is always override by the node's name if theirs keys are conflicted.

I'm still not sure I understood properly what you meant, sorry. But let's not hang up in this specific subject... 
Answering your questions:

1) It's just another way "overriding" or "keeping" attribute values, but this actually informs the underlining code that we don't care about the node contents. Based on that you could apply some optimizations to avoid expanding that node content, hence gaining performance.

2) I don't have a problem with the word "override", even though English is not my main language, I think this what's called the "imperative mood", which is the verbal mood to express commands. Using "overridden_by" actually inverts the login, because you are expressing the "current state", since "overridden" is the past form of "override". 
If you think of it as a sentence, it makes more sense:
- Use strategy: Ignore attribute!
- Use strategy: Ignore node!
- Use strategy: Override attribute!
- Use strategy: Override node!

3) You are right! Using my previous example, this is the only scenario where it not 100% clear reading the code that this is about attributes. But since the program does not have any other kind of strategy, I'd just document that. But I don't want to push specific semantics, do whatever you feel more comfortable, those were only suggestions 😄.

**Comment by xinz** [comment]
Hello, 

This is my pleasure if this library is useful for you, but the following changes make this library more complex, I would like to enhance it to resolve the practical problems if we are facing, so I may not implement it as below (so far), I still would add the `ignore_attribute` as true | false | {false, prefix} to decide process attribute(s) or not, is it acceptable for your using? 

- Use strategy: Ignore attribute!
- Use strategy: Ignore node!
- Use strategy: Override attribute!
- Use strategy: Override node!

Thanks again for talking with you, and make me gain more while maintain this library.

**Comment by thiagomajesk** [comment]
@xinz I'm sorry if I got a little bit off-topic. Objectively, yes! Thanks for your patience.

**Comment by xinz** [comment]
Thanks, I will do some update for it.

**Comment by xinz** [comment]
Base on the above discussion, here is the current final implements about `ignore_attribute`

```elixir
xml = """
  <thread version="1">
    <title color="red" font="16">Hello</title>
    <items size="3">
      <item font="12">item1</item>
      <item font="12">item2</item>
      <item font="12">item3</item>
    </items>
  </thread>
"""

SAXMap.from_string(xml)

# return
{:ok,
 %{
   "thread" => %{
     "items" => %{"item" => ["item1", "item2", "item3"]},
     "title" => "Hello"
   }
 }}

SAXMap.from_string(xml, ignore_attribute: false)

# return
{:ok,
  %{
    "thread" => %{
      "content" => %{
        "items" => %{
          "content" => %{
            "item" => [
              %{"content" => "item1", "font" => "12"},
              %{"content" => "item2", "font" => "12"},
              %{"content" => "item3", "font" => "12"}
            ]
          },
          "size" => "3"
        },
        "title" => %{"color" => "red", "content" => "Hello", "font" => "16"}
      },
      "version" => "1"
    }
  }}

SAXMap.from_string(xml, ignore_attribute: {false, "@"})

# return
{:ok,
  %{
    "thread" => %{
      "@version" => "1",
      "content" => %{
        "items" => %{
          "@size" => "3",
          "content" => %{
            "item" => [
              %{"@font" => "12", "content" => "item1"},
              %{"@font" => "12", "content" => "item2"},
              %{"@font" => "12", "content" => "item3"}
            ]
          }
        },
        "title" => %{"@color" => "red", "@font" => "16", "content" => "Hello"}
      }
    }
  }}
```

**Comment by xinz** [comment]
This function release in [1.0.0](https://hex.pm/packages/sax_map/1.0.0)

**Comment by xinz** [comment]
Close it since this function is added.
